import { Facebook, Instagram, Linkedin, Twitter } from "lucide-react";

export const ListItems = [
  { name: "anasayfa", href: "/" },
  { name: "warsa", href: "/#" },
  { name: "blog", href: "/#" },
  { name: "temsilci", href: "/#" },
  { name: "iletisim", href: "/#" },
];

export const Counties = [
  "Ankara",
  "İstanbul",
  "Konya",
  "Adana",
  "Kayseri",
  "Trabzon",
  "Bursa",
  "Eskişehir",
  "İzmir",
  "Antalya",
  "Çanakkale",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Düzce",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Isparta",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Mardin",
  "Mersin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Osmaniye",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Şanlıurfa",
  "Şırnak",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Uşak",
  "Van",
  "Yalova",
  "Yozgat",
  "Zonguldak",
];

export const Images = [
  {
    src: "https://picsum.photos/500/500",
    alt: "Boş",
    width: 500,
    height: 500,
    text: "Boş Arsa",
  },
  {
    src: "https://picsum.photos/500/500",
    alt: "Tarım",
    width: 500,
    height: 500,
    text: "Tarım Arsası",
  },
  {
    src: "https://picsum.photos/500/500",
    alt: "Hazır",
    width: 500,
    height: 500,
    text: "Hazır Arsa",
  },
  {
    src: "https://picsum.photos/500/500",
    alt: "Hazır",
    width: 500,
    height: 500,
    text: "Hazır Arsa",
  },
  {
    src: "https://picsum.photos/500/500",
    alt: "Hazır",
    width: 500,
    height: 500,
    text: "Hazır Arsa",
  },
  {
    src: "https://picsum.photos/500/500",
    alt: "Hazır",
    width: 500,
    height: 500,
    text: "Hazır Arsa",
  },
  {
    src: "https://picsum.photos/500/500",
    alt: "Hazır",
    width: 500,
    height: 500,
    text: "Hazır Arsa",
  },
  {
    src: "https://picsum.photos/500/500",
    alt: "Hazır",
    width: 500,
    height: 500,
    text: "Hazır Arsa",
  },
];

export const FooterLeftLinks = [
  { name: "Satılık Arazi", href: "/" },
  { name: "Kiralık Arazi", href: "/" },
  { name: "Temsilciler", href: "/" },
];

export const FooterMiddleLinks = [
  { name: "Yardım Merkezi", href: "/" },
  { name: "Temsilci Bul", href: "/" },
  { name: "Blog", href: "/" },
  { name: "Kredi Hesaplama", href: "/" },
  { name: "Servisler", href: "/" },
  { name: "Hakkımızda", href: "/" },
  { name: "Proje Akışı", href: "/" },
  { name: "Yorumlar", href: "/" },
  { name: "İletişim", href: "/" },
];

export const FooterRightLinks = [
  { name: "Facebook", href: "/", Icon: Facebook },
  { name: "Twitter", href: "/", Icon: Instagram },
  { name: "Instagram", href: "/", Icon: Twitter },
  { name: "Linkedin", href: "/", Icon: Linkedin },
];

export const FooterMetadata = [
  { name: "Site Haritası", href: "/" },
  { name: "Gizlilik", href: "/" },
  { name: "Koşullar", href: "/" },
];
